---
title: "Department of Energy Budgetary Requests and Allocations"
author: "Jing-Jing Shen"
description: "Change in DOE budgetary requests to Congress and the subsequent appropriations"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

For my final project, I am hoping to examine budgetary data from the Department of Energy over the last several decades (1978--). As part of my senior thesis in government, I am looking into how federal climate and energy policy has shaped research priorities at national laboratories of the DOE, particularly in renewable energy, and I would like to bolster this study with an investigation into the DOE's budgetary history. More specifically, I would like to gain a deeper understanding of the relationship between DOE budget requests to Congress and the ultimate appropriations made, the breakdown of this budget by sector and research area, as well as what policy factors and/or energy economics may be related to this budgetary information. 

--

From Sample Project

I am interested in exploring data related to immigration enforcement and immigration preferences. A working project with Asya Magazinnik (Massachusetts Institute of Technology) explores how county-level compliance of Sheriff's offices with ICE detainer requests relates to ideal point estimates of immigration preferences. Specifically: our project asks whether the public's immigration preferences, restrictive or accommodating, influences how local law enforcement agencies comply with bureaucratic delegation from ICE.

To investigate this relationship, we are relying on data from three different sources:

1. [Transactional Records Access Clearinghouse (TRAC)](https://trac.syr.edu/immigration/) data on detainer requests sent to county Sheriff's offices from the Department of Homeland Security's sub-agency Immigration Customs and Enforcement (ICE);

2. [Coooperative Election Study (CES)](https://cces.gov.harvard.edu/) data on immigration policy preferences; and

3. novel data of county-level Sheriff elections and electoral type--partisan or non-partisan elections, non-electoral appointment.

TRAC data provides us with our outcome variable, the proportion of ICE detainer requests that are complied with; CES data provides us with our explanatory variable, public immigration policy preferences; and the Sheriff electoral data provides us with a grouping variable.



